### ISSUE TITLE
Call Bot Not Active or Generating Summaries

### ISSUE THREAD

**Issue by reidellawfirm** [nextcloud/call_summary_bot#30]
Hello, I have installed the Call Summary Bot from the NC Apps module and also made sure to flip the switch option under Conversation Settings > Call Summary to enable it in a couple of our Talk chats. I haven't seen any changes to the Talk room and no bot was added (not sure if there is a notification for that). Whenever we have a call no summary is generated and no todos are indicated as tasks. 

What can I do to troubleshoot this? I am using Nextcloud AIO ([Nextcloud Hub 6](https://nextcloud.com/) (27.1.4)). Please let me know what I am missing or how I can troubleshoot this as this feature will be very helpful for my team.

**Comment by reidellawfirm** [comment]
1. Yes, it is listed so it appears to be installed.  

occ $ talk:bot:list
+----+-----------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------
--+-------+-------------------+
| id | name                  | description                                                                                                                                                                                     | error_coun
t | state | features          |
+----+-----------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------
--+-------+-------------------+
| 1  | Call summary          | Call summary (British English) - The call summary bot posts an overview message after the call listing all participants and outlining tasks                                                     | 0         
  | 1     | webhook, response |
| 2  | Protokoll             | Protokoll (Deutsch (Persönlich: Du)) - Der Anruf-Zusammenfassungs-Bot veröffentlicht nach der Unterhaltung eine Übersichtsnachricht, in der alle Teilnehmenden und die Aufgaben aufgeführt sind | 0         
  | 1     | webhook, response |
| 3  | Resumen de la llamada | Resumen de la llamada (Español (España)) - El bot de resumen de llamada publica un mensaje de visión general listando a todos los participantes y delineando tareas                             | 0         
  | 1     | webhook, response |
| 4  | Résumé de l'appel     | Résumé de l'appel (Français) - The call summary bot posts an overview message after the call listing all participants and outlining tasks                                                       | 0         
  | 1     | webhook, response |
| 5  | ملخص المكالمة         | ملخص المكالمة (اللغة العربية) - يقوم روبوت "ملخص المكالمة"بنشر رسالة عامة بعد المكالمة يسرد فيها جميع المشاركين و يحدد المهام                                                                   | 0         
  | 1     | webhook, response |
| 6  | Resumo da chamada     | Resumo da chamada (Português Brasileiro) - O bot de resumo da chamada publica uma mensagem de visão geral após a chamada, listando todos os participantes e descrevendo as tarefas              | 0         
  | 1     | webhook, response |
| 7  | Çağrı özeti           | Çağrı özeti (Türkçe) - Çağrı özeti botu, çağrıdan sonra tüm katılımcıları listeleyen ve görevleri özetleyen bir özet iletisi gönderir.                                                          | 0         
  | 1     | webhook, response |
| 8  | 通话摘要              | 通话摘要 (简体中文) - 通话摘要机器人会在通话结束后发布一条概述信息，列出所有与会者并概述各项任务                                                                                                | 0           | 1     | webhook, response |
| 9  | Call summary          | Call summary (British English) - The call summary bot posts an overview message after the call listing all participants and outlining tasks                                                     | 0         
  | 1     | webhook, response |
| 10 | Protokoll             | Protokoll (Deutsch (Persönlich: Du)) - Der Anruf-Zusammenfassungs-Bot veröffentlicht nach der Unterhaltung eine Übersichtsnachricht, in der alle Teilnehmenden und die Aufgaben aufgeführt sind | 0         
  | 1     | webhook, response |
| 11 | Resumen de la llamada | Resumen de la llamada (Español (España)) - El bot de resumen de llamada publica un mensaje de visión general listando a todos los participantes y delineando tareas                             | 0         
  | 1     | webhook, response |
| 12 | Résumé de l'appel     | Résumé de l'appel (Français) - The call summary bot posts an overview message after the call listing all participants and outlining tasks                                                       | 0         
  | 1     | webhook, response |
| 13 | ملخص المكالمة         | ملخص المكالمة (اللغة العربية) - يقوم روبوت "ملخص المكالمة"بنشر رسالة عامة بعد المكالمة يسرد فيها جميع المشاركين و يحدد المهام                                                                   | 0         
  | 1     | webhook, response |
| 14 | Resumo da chamada     | Resumo da chamada (Português Brasileiro) - O bot de resumo da chamada publica uma mensagem de visão geral após a chamada, listando todos os participantes e descrevendo as tarefas              | 0         
  | 1     | webhook, response |
| 15 | Çağrı özeti           | Çağrı özeti (Türkçe) - Çağrı özeti botu, çağrıdan sonra tüm katılımcıları listeleyen ve görevleri özetleyen bir özet iletisi gönderir.                                                          | 0         
  | 1     | webhook, response |
| 16 | 通话摘要              | 通话摘要 (简体中文) - 通话摘要机器人会在通话结束后发布一条概述信息，列出所有与会者并概述各项任务                                                                                                | 0           | 1     | webhook, response |
+----+-----------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------
--+-------+-------------------+

**Comment by reidellawfirm** [comment]
2. Ah ok, I think I see the issue. So two secret hashes are listed. The correct one is listed for a different domain. We recently migrated a standard Nextcloud Hub install to a NC AIO install.

So it seems I need to manually revise the call-summary-bot:list to match the new server and hash? Are there any details on how to do that?

**Comment by nickvergessen** [comment]
easiest is probably to:

1. Remove all bots in Talk: `occ talk:bot:remove 1`, `occ talk:bot:remove 2` until `occ talk:bot:remove 16`
2. Remove all Backends in call summary bot: `occ call-summary-bot:delete ID` with ID being all values listed in `occ call-summary-bot:list`
3. Afterwards disable and reenable the call_summary_bot app: `occ app:disable call_summary_bot` and `occ app:enable call_summary_bot`

**Comment by reidellawfirm** [comment]
Ok, so I did go through your steps. I still wasn't able to get the call summary bot to work. No list of attendees and no todos listed from call. 

I noticed when I run occ call-summary-bot:list that both the old and new server still come up under backend with their own secret key. 

I am assuming I need to find a way to remove the old backend server credentials from re-populating when enabling the call summary bot. Are there other artifacts of the old server backend I should look for to delete?

**Comment by nickvergessen** [comment]
`occ call-summary-bot:delete <ID>` exists and should help with that

**Comment by reidellawfirm** [comment]
So I do get the response that the secret was deleted with that delete command but now confirming after with list command that the list is identical before and after. See attached. 

Do I need to go into server config files and manually delete the duplicate server ID
 somewhere?

![Screenshot_20231213_065921_Firefox](https://github.com/nextcloud/call_summary_bot/assets/75231847/cef33cf0-98ca-40f2-bf45-503cd3c16235)

**Comment by nickvergessen** [comment]
It's in the database oc_appconfig table

**Comment by nickvergessen** [comment]
Deleting command is fixed in https://github.com/nextcloud/call_summary_bot/pull/33

**Comment by nickvergessen** [comment]
I added a new command `occ call-summary-bot:repair` in #34 and will release a new version 1.0.1 tonight.
You can then update to that version and run the command once.

**Comment by nickvergessen** [comment]
It's uploaded and should be offered as an update soon:
https://apps.nextcloud.com/apps/call_summary_bot

**Comment by reidellawfirm** [comment]
When I updated and ran the repair command, the response I got back was [object] [object]. 

Though I can now delete the secret to the old server. I ran through the steps again to test you gave in the first comment but I still can't get the summary bot to work. 

After disabling the call summary bot app, when I run occ $ talk:bot:list I still see the full list of bots but it goes from 1 through 8 and then continues from 17 through 24. (See attached).

Any other ideas on troubleshooting steps? I currently have the call summary bot disabled but still have the bots coming up in the list as shown. I guess I need to delete these manually from the database files?

**Comment by reidellawfirm** [comment]
Can anyone help me with this? Or do I have to open a new issue? The call summary bot still does not work for me.

**Comment by nickvergessen** [comment]
Copied from #38

---


I recently submitted an issue (#30  ) where my call summary bot was not working. The issue was closed after some bug was identified but the fix did not help me and I am trying to completely remove the call summary bot from my server so I can try to reinstall it fresh. 

I am attaching various screencaps showing my current status. Please let me know what steps I can take to troubleshoot this and hopefully reinstall the bot fresh.

Screencap 1: showing the call summary bot is not installed per NC Apps
![Screenshot from 2023-12-28 17-17-00](https://github.com/nextcloud/call_summary_bot/assets/75231847/6a629e46-5674-49b9-9861-a24eecef6788)

Screencap 2: showing the talk bot list per OCC, bot sure if it matters but note the bots go from 1-8 and then repeat starting at 17
![Screenshot from 2023-12-28 17-16-22](https://github.com/nextcloud/call_summary_bot/assets/75231847/39d7dc00-a506-4aee-9e7a-4871317b3420)

Screencap 3: showing the talk bot list details per OCC; note that the first set of bots are for an older server (signal.) which existed before a migration; the current server is cloud.; 
![Screenshot from 2023-12-28 17-18-08](https://github.com/nextcloud/call_summary_bot/assets/75231847/2c1a1335-d5e9-4462-b8b1-8a8fadb9dddd)

Screencap 4: detailed lost continued
![Screenshot from 2023-12-28 17-18-13](https://github.com/nextcloud/call_summary_bot/assets/75231847/d36537e4-b8f7-4585-9c7b-69a1c370a292)

Screencap 5: call summary bot commands not recognized in OCC
![Screenshot from 2023-12-28 17-19-19](https://github.com/nextcloud/call_summary_bot/assets/75231847/18566bb4-9c2a-4aed-810d-5e9bc13544d1)

**Comment by nickvergessen** [comment]
Screenshot 1 and 5 indicate that the app is not enabled at the moment.
If that is still your current state, let's do the following occ commands:

```
talk:bot:uninstall 1
talk:bot:uninstall 2
talk:bot:uninstall 3
talk:bot:uninstall 4
talk:bot:uninstall 5
talk:bot:uninstall 6
talk:bot:uninstall 7
talk:bot:uninstall 8
talk:bot:uninstall 9
talk:bot:uninstall 10
talk:bot:uninstall 11
talk:bot:uninstall 12
talk:bot:uninstall 13
talk:bot:uninstall 14
talk:bot:uninstall 15
talk:bot:uninstall 16
talk:bot:uninstall 17
talk:bot:uninstall 18
talk:bot:uninstall 19
talk:bot:uninstall 20
talk:bot:uninstall 21
talk:bot:uninstall 22
talk:bot:uninstall 23
talk:bot:uninstall 24
```

Afterwards enable the app again from screenshot 1

**Comment by reidellawfirm** [comment]
Thank you, this did the trick. Finally had a chance to update and run through your instructions. 

Uninstalled the extra bots and was able to successfully reinstall and enable the call summary bot to work. For future reference, anyone migrating their domain will likely want to disable and uninstall the call summary bot before the migration and then re-install and enable after the migration to prevent any leftover and conflicting bot IDs/APIs.
